# Generated by Django 5.1.1 on 2024-10-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_author_bio_remove_book_published_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritebook',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='books.book'),
        ),
        migrations.RemoveField(
            model_name='favoritebook',
            name='book',
        ),
    ]
